; Code generated by IDL 8.5.1.
  plot0 = Plot(x, y, $  ; <- Data required
    XTICKFONT_SIZE=20.000000, $
    YTICKFONT_SIZE=20.000000, $
    XTITLE='$log_{10}$ Temperature ($log_{10}$ K)', $
    THICK=4.00000, $
    YTITLE='$log_{10}$ DEM (arbitrary units)', $
    DIMENSIONS=[1030,876], $
    TITLE='Mean EIT DEM')
  title = plot0.TITLE
  title.FONT_SIZE = 20.000000

end
